### ISSUE TITLE
test generator usage

### ISSUE THREAD

**Issue by pratyush1223** [me1stplease/TestDataGenerator#1]
Can you bit more explain about the usage of this generator. I am working on a similar project.Looking forward to know more about the usage

**Comment by me1stplease** [comment]
Hi Pratyush, I'm currently working on this project its not yet finished. The goal is to create a tool for big data testers. This tool helps them test data pipelines and validations before using real data. In the project, I've included two main features. One generates fake data randomly using a tool called Faker, but I'm facing an issue with data integrity because each attribute is completely different from the others. The second feature generates data using GAN, but I'm concerned about data security. I want to integrate a solution to encrypt personally identifiable information (PII) before making an API call and decrypt it after data generation to enhance security.

**Comment by pratyush1223** [comment]
Thank You me1stPlease, I have gone through your repo and I am currently working on the same thing. I am a fresher so I just wanted to know more about your repo. There's a lot of file so I am confused about GAN. Can I just connect with you to get a more bit of idea about what to do? Do let me know where can I connect.

**Comment by me1stplease** [comment]
Actually, I'm out of station right now for some reason but I'll be happy discussing this topic. You can surely connect with me at https://www.linkedin.com/in/yourstruly-mahtab. Thanks.
